services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - laravel

    nginx:
        image: nginx:latest
        container_name: laravel_nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - .:/var/www
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/ssl:/etc/nginx/ssl
        networks:
            - laravel
        depends_on:
            - app

networks:
    laravel:
